//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region ClientContact
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ClientContact :
        global::LightSwitchApplication.ClientContact.DetailsClass.IImplementation
    {
        partial void OnClientContact_ClientChanged()
        {
            this.___OnPropertyChanged("ClientContact_Client");
            this.___OnPropertyChanged("Client");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnContactNameChanged()
        {
            this.___OnPropertyChanged("ContactName");
        }
        
        partial void OnContactJobDescriptionChanged()
        {
            this.___OnPropertyChanged("ContactJobDescription");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientContact.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __Client
        {
            get
            {
                if (this.___Client == null)
                {
                    this.___Client = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "Client",
                        new string[] { "ClientContact_Client" },
                        e => global::System.Object.Equals(e.Id, this.ClientContact_Client),
                        () => this._Client,
                        e => this._Client = e);
                }
                return this.___Client;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___Client;
        
    }
    #endregion
    
    #region Client
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnClientNameChanged()
        {
            this.___OnPropertyChanged("ClientName");
        }
        
        partial void OnAddressLine1Changed()
        {
            this.___OnPropertyChanged("AddressLine1");
        }
        
        partial void OnAddressLine2Changed()
        {
            this.___OnPropertyChanged("AddressLine2");
        }
        
        partial void OnAddressLine3Changed()
        {
            this.___OnPropertyChanged("AddressLine3");
        }
        
        partial void OnAddressLine4Changed()
        {
            this.___OnPropertyChanged("AddressLine4");
        }
        
        partial void OnAddressLine5Changed()
        {
            this.___OnPropertyChanged("AddressLine5");
        }
        
        partial void OnPostCodeChanged()
        {
            this.___OnPropertyChanged("PostCode");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhone1Changed()
        {
            this.___OnPropertyChanged("Phone1");
        }
        
        partial void OnPhone2Changed()
        {
            this.___OnPropertyChanged("Phone2");
        }
        
        partial void OnFaxChanged()
        {
            this.___OnPropertyChanged("Fax");
        }
        
        partial void OnWebsiteChanged()
        {
            this.___OnPropertyChanged("Website");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> __Projects
        {
            get
            {
                if (this.___Projects == null)
                {
                    this.___Projects = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Projects",
                        () => this._Projects,
                        e => global::System.Object.Equals(e.Client_Project, this.Id));
                }
                return this.___Projects;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> ___Projects;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.ClientContacts
        {
            get
            {
                return this.ClientContacts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientContact> __ClientContacts
        {
            get
            {
                if (this.___ClientContacts == null)
                {
                    this.___ClientContacts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientContact>(
                        this,
                        "ClientContacts",
                        () => this._ClientContacts,
                        e => global::System.Object.Equals(e.ClientContact_Client, this.Id));
                }
                return this.___ClientContacts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientContact> ___ClientContacts;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnEmployeeImageChanged()
        {
            this.___OnPropertyChanged("EmployeeImage");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.ProjectResources
        {
            get
            {
                return this.ProjectResources;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource> __ProjectResources
        {
            get
            {
                if (this.___ProjectResources == null)
                {
                    this.___ProjectResources = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource>(
                        this,
                        "ProjectResources",
                        () => this._ProjectResources,
                        e => global::System.Object.Equals(e.Resource_ProjectResource, this.Id));
                }
                return this.___ProjectResources;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource> ___ProjectResources;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> __Projects
        {
            get
            {
                if (this.___Projects == null)
                {
                    this.___Projects = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Projects",
                        () => this._Projects,
                        e => global::System.Object.Equals(e.Project_Employee, this.Id));
                }
                return this.___Projects;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Project> ___Projects;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeSkillsCollection
        {
            get
            {
                return this.EmployeeSkillsCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeSkills> __EmployeeSkillsCollection
        {
            get
            {
                if (this.___EmployeeSkillsCollection == null)
                {
                    this.___EmployeeSkillsCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeSkills>(
                        this,
                        "EmployeeSkillsCollection",
                        () => this._EmployeeSkillsCollection,
                        e => global::System.Object.Equals(e.EmployeeSkills_Employee, this.Id));
                }
                return this.___EmployeeSkillsCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeSkills> ___EmployeeSkillsCollection;
        
    }
    #endregion
    
    #region EmployeeSkills
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeSkills :
        global::LightSwitchApplication.EmployeeSkills.DetailsClass.IImplementation
    {
        partial void OnEmployeeSkills_EmployeeChanged()
        {
            this.___OnPropertyChanged("EmployeeSkills_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnSkillChanged()
        {
            this.___OnPropertyChanged("Skill");
        }
        
        partial void OnSkillYearsChanged()
        {
            this.___OnPropertyChanged("SkillYears");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeSkills.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "EmployeeSkills_Employee" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeSkills_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
    }
    #endregion
    
    #region ProjectResource
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectResource :
        global::LightSwitchApplication.ProjectResource.DetailsClass.IImplementation
    {
        partial void OnResource_ProjectResourceChanged()
        {
            this.___OnPropertyChanged("Resource_ProjectResource");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnProjectResource_ProjectChanged()
        {
            this.___OnPropertyChanged("ProjectResource_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectResource.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "Resource_ProjectResource" },
                        e => global::System.Object.Equals(e.Id, this.Resource_ProjectResource),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectResource.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "ProjectResource_Project" },
                        e => global::System.Object.Equals(e.Id, this.ProjectResource_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectResource.DetailsClass.IImplementation.ProjectResourceTasks
        {
            get
            {
                return this.ProjectResourceTasks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask> __ProjectResourceTasks
        {
            get
            {
                if (this.___ProjectResourceTasks == null)
                {
                    this.___ProjectResourceTasks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask>(
                        this,
                        "ProjectResourceTasks",
                        () => this._ProjectResourceTasks,
                        e => global::System.Object.Equals(e.ProjectResourceTask_ProjectResource, this.Id));
                }
                return this.___ProjectResourceTasks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask> ___ProjectResourceTasks;
        
    }
    #endregion
    
    #region ProjectResourceTask
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectResourceTask :
        global::LightSwitchApplication.ProjectResourceTask.DetailsClass.IImplementation
    {
        partial void OnProjectResourceTask_ProjectResourceChanged()
        {
            this.___OnPropertyChanged("ProjectResourceTask_ProjectResource");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnProjectResourceTask_ProjectTaskChanged()
        {
            this.___OnPropertyChanged("ProjectResourceTask_ProjectTask");
            this.___OnPropertyChanged("ProjectTask");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectResourceTask.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.ProjectResource)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectResource> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectResource>(
                        this,
                        "AssignedTo",
                        new string[] { "ProjectResourceTask_ProjectResource" },
                        e => global::System.Object.Equals(e.Id, this.ProjectResourceTask_ProjectResource),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectResource> ___AssignedTo;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectResourceTask.DetailsClass.IImplementation.ProjectTask
        {
            get
            {
                return this.ProjectTask;
            }
            set
            {
                this.ProjectTask = (global::LightSwitchApplication.Implementation.ProjectTask)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectTask> __ProjectTask
        {
            get
            {
                if (this.___ProjectTask == null)
                {
                    this.___ProjectTask = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectTask>(
                        this,
                        "ProjectTask",
                        new string[] { "ProjectResourceTask_ProjectTask" },
                        e => global::System.Object.Equals(e.Id, this.ProjectResourceTask_ProjectTask),
                        () => this._ProjectTask,
                        e => this._ProjectTask = e);
                }
                return this.___ProjectTask;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ProjectTask> ___ProjectTask;
        
    }
    #endregion
    
    #region ProjectRisk
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectRisk :
        global::LightSwitchApplication.ProjectRisk.DetailsClass.IImplementation
    {
        partial void OnProjectRisk_ProjectChanged()
        {
            this.___OnPropertyChanged("ProjectRisk_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRiskTitleChanged()
        {
            this.___OnPropertyChanged("RiskTitle");
        }
        
        partial void OnRiskDescriptionChanged()
        {
            this.___OnPropertyChanged("RiskDescription");
        }
        
        partial void OnControlMeasuresChanged()
        {
            this.___OnPropertyChanged("ControlMeasures");
        }
        
        partial void OnLikelihoodChanged()
        {
            this.___OnPropertyChanged("Likelihood");
        }
        
        partial void OnImpactChanged()
        {
            this.___OnPropertyChanged("Impact");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectRisk.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "ProjectRisk_Project" },
                        e => global::System.Object.Equals(e.Id, this.ProjectRisk_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
    }
    #endregion
    
    #region Project
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
        partial void OnProject_EmployeeChanged()
        {
            this.___OnPropertyChanged("Project_Employee");
            this.___OnPropertyChanged("ProjectManager");
        }
        
        partial void OnClient_ProjectChanged()
        {
            this.___OnPropertyChanged("Client_Project");
            this.___OnPropertyChanged("Client");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnProjectReferenceChanged()
        {
            this.___OnPropertyChanged("ProjectReference");
        }
        
        partial void OnProjectNameChanged()
        {
            this.___OnPropertyChanged("ProjectName");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnEndDateChanged()
        {
            this.___OnPropertyChanged("EndDate");
        }
        
        partial void OnProrityChanged()
        {
            this.___OnPropertyChanged("Prority");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnBudgetChanged()
        {
            this.___OnPropertyChanged("Budget");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectTasks
        {
            get
            {
                return this.ProjectTasks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectTask> __ProjectTasks
        {
            get
            {
                if (this.___ProjectTasks == null)
                {
                    this.___ProjectTasks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectTask>(
                        this,
                        "ProjectTasks",
                        () => this._ProjectTasks,
                        e => global::System.Object.Equals(e.ProjectTask_Project, this.Id));
                }
                return this.___ProjectTasks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectTask> ___ProjectTasks;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectResources
        {
            get
            {
                return this.ProjectResources;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource> __ProjectResources
        {
            get
            {
                if (this.___ProjectResources == null)
                {
                    this.___ProjectResources = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource>(
                        this,
                        "ProjectResources",
                        () => this._ProjectResources,
                        e => global::System.Object.Equals(e.ProjectResource_Project, this.Id));
                }
                return this.___ProjectResources;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResource> ___ProjectResources;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectManager
        {
            get
            {
                return this.ProjectManager;
            }
            set
            {
                this.ProjectManager = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __ProjectManager
        {
            get
            {
                if (this.___ProjectManager == null)
                {
                    this.___ProjectManager = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "ProjectManager",
                        new string[] { "Project_Employee" },
                        e => global::System.Object.Equals(e.Id, this.Project_Employee),
                        () => this._ProjectManager,
                        e => this._ProjectManager = e);
                }
                return this.___ProjectManager;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___ProjectManager;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __Client
        {
            get
            {
                if (this.___Client == null)
                {
                    this.___Client = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "Client",
                        new string[] { "Client_Project" },
                        e => global::System.Object.Equals(e.Id, this.Client_Project),
                        () => this._Client,
                        e => this._Client = e);
                }
                return this.___Client;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___Client;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectRisks
        {
            get
            {
                return this.ProjectRisks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectRisk> __ProjectRisks
        {
            get
            {
                if (this.___ProjectRisks == null)
                {
                    this.___ProjectRisks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectRisk>(
                        this,
                        "ProjectRisks",
                        () => this._ProjectRisks,
                        e => global::System.Object.Equals(e.ProjectRisk_Project, this.Id));
                }
                return this.___ProjectRisks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectRisk> ___ProjectRisks;
        
    }
    #endregion
    
    #region ProjectTask
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectTask :
        global::LightSwitchApplication.ProjectTask.DetailsClass.IImplementation
    {
        partial void OnProjectTask_ProjectChanged()
        {
            this.___OnPropertyChanged("ProjectTask_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnTitleChanged()
        {
            this.___OnPropertyChanged("Title");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnDueDateChanged()
        {
            this.___OnPropertyChanged("DueDate");
        }
        
        partial void OnPriorityChanged()
        {
            this.___OnPropertyChanged("Priority");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnPercentCompletedChanged()
        {
            this.___OnPropertyChanged("PercentCompleted");
        }
        
        partial void OnDateStartedChanged()
        {
            this.___OnPropertyChanged("DateStarted");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectTask.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "ProjectTask_Project" },
                        e => global::System.Object.Equals(e.Id, this.ProjectTask_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ProjectTask.DetailsClass.IImplementation.ProjectResourceTasks
        {
            get
            {
                return this.ProjectResourceTasks;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask> __ProjectResourceTasks
        {
            get
            {
                if (this.___ProjectResourceTasks == null)
                {
                    this.___ProjectResourceTasks = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask>(
                        this,
                        "ProjectResourceTasks",
                        () => this._ProjectResourceTasks,
                        e => global::System.Object.Equals(e.ProjectResourceTask_ProjectTask, this.Id));
                }
                return this.___ProjectResourceTasks;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectResourceTask> ___ProjectResourceTasks;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.ClientContact))
            {
                return new global::LightSwitchApplication.Implementation.ClientContact();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeSkills))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeSkills();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectResource))
            {
                return new global::LightSwitchApplication.Implementation.ProjectResource();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectResourceTask))
            {
                return new global::LightSwitchApplication.Implementation.ProjectResourceTask();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectRisk))
            {
                return new global::LightSwitchApplication.Implementation.ProjectRisk();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectTask))
            {
                return new global::LightSwitchApplication.Implementation.ProjectTask();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.ClientContact) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ClientContact);
            }
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.EmployeeSkills) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeSkills);
            }
            if (typeof(global::LightSwitchApplication.ProjectResource) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectResource);
            }
            if (typeof(global::LightSwitchApplication.ProjectResourceTask) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectResourceTask);
            }
            if (typeof(global::LightSwitchApplication.ProjectRisk) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectRisk);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.ProjectTask) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectTask);
            }
            return null;
        }
    }
}
