

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class ClientContact : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ClientContact entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ClientContact()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ClientContact(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ClientContact> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ClientContact.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientContact_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientContact_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContactName
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactName);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContactJobDescription
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactJobDescription);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactJobDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactJobDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactJobDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactJobDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Phone
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Phone);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Phone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Client Client
        {
            get
            {
                return global::LightSwitchApplication.ClientContact.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client);
            }
            set
            {
                global::LightSwitchApplication.ClientContact.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Client_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ClientContact,
                global::LightSwitchApplication.ClientContact.DetailsClass,
                global::LightSwitchApplication.ClientContact.DetailsClass.IImplementation,
                global::LightSwitchApplication.ClientContact.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>.Entry
                __ClientContactEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>.Entry(
                    global::LightSwitchApplication.ClientContact.DetailsClass.__ClientContact_CreateNew,
                    global::LightSwitchApplication.ClientContact.DetailsClass.__ClientContact_Created,
                    global::LightSwitchApplication.ClientContact.DetailsClass.__ClientContact_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ClientContact __ClientContact_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ClientContact> es)
            {
                return new global::LightSwitchApplication.ClientContact(es);
            }
            private static void __ClientContact_Created(global::LightSwitchApplication.ClientContact e)
            {
                e.ClientContact_Created();
            }
            private static bool __ClientContact_AllowSaveWithErrors(global::LightSwitchApplication.ClientContact e)
            {
                bool result = false;
                e.ClientContact_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ClientContact.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> ContactName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> ContactJobDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ContactJobDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> Phone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Phone) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client> Client
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string ContactName { get; set; }
                new string ContactJobDescription { get; set; }
                new string Email { get; set; }
                new string Phone { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Client { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    ContactName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "ContactName",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactName_OnValueChanged);
                private static void _ContactName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactName, sf);
                }
                private static bool _ContactName_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.ContactName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactName_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactName_Validate(r);
                }
                private static string _ContactName_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactName;
                }
                private static void _ContactName_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContactName = v;
                }
                private static void _ContactName_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.ContactName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    ContactJobDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "ContactJobDescription",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ContactJobDescription_OnValueChanged);
                private static void _ContactJobDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactJobDescription, sf);
                }
                private static bool _ContactJobDescription_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.ContactJobDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactJobDescription_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactJobDescription_Validate(r);
                }
                private static string _ContactJobDescription_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactJobDescription;
                }
                private static void _ContactJobDescription_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContactJobDescription = v;
                }
                private static void _ContactJobDescription_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.ContactJobDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "Phone",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Phone_OnValueChanged);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static bool _Phone_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Phone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Phone_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Phone_Validate(r);
                }
                private static string _Phone_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Phone;
                }
                private static void _Phone_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Phone = v;
                }
                private static void _Phone_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Phone_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client>.Entry
                    Client = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client>.Entry(
                        "Client",
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_Stub,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_Validate,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_GetCoreImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_GetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_SetImplementationValue,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_Refresh,
                        global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties._Client_OnValueChanged);
                private static void _Client_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientContact.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client>.Data> c, global::LightSwitchApplication.ClientContact.DetailsClass d, object sf)
                {
                    c(d, ref d._Client, sf);
                }
                private static bool _Client_ComputeIsReadOnly(global::LightSwitchApplication.ClientContact e)
                {
                    bool result = false;
                    e.Client_IsReadOnly(ref result);
                    return result;
                }
                private static void _Client_Validate(global::LightSwitchApplication.ClientContact e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Client_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Client_GetCoreImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.ImplementationEntity.Client;
                }
                private static global::LightSwitchApplication.Client _Client_GetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Client, global::LightSwitchApplication.Client.DetailsClass>(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass d, global::LightSwitchApplication.Client v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client, ref d._Client, (i, ev) => i.Client = ev, v);
                }
                private static void _Client_Refresh(global::LightSwitchApplication.ClientContact.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ClientContact.DetailsClass.PropertySetProperties.Client, ref d._Client);
                }
                private static void _Client_OnValueChanged(global::LightSwitchApplication.ClientContact e)
                {
                    e.Client_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _ContactName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _ContactJobDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _Phone;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientContact, global::LightSwitchApplication.ClientContact.DetailsClass, global::LightSwitchApplication.Client>.Data _Client;
            
        }
    
        #endregion
    }
    
    #endregion
}
