

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class ProjectTask : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ProjectTask entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectTask()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ProjectTask(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectTask> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ProjectTask.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTask_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectTask_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DueDate);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DueDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DueDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DueDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DueDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Priority
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Priority);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Priority, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Priority_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Priority_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Priority_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Status
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Status);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Status, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal PercentCompleted
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.PercentCompleted);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.PercentCompleted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PercentCompleted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PercentCompleted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PercentCompleted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateStarted
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateStarted);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateStarted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStarted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStarted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateStarted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateCompleted);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateCompleted, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateCompleted_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Project Project
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project);
            }
            set
            {
                global::LightSwitchApplication.ProjectTask.DetailsClass.SetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Project_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Project_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Project_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProjectResourceTask> ProjectResourceTasks
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ProjectResourceTasks);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProjectResourceTask> ProjectResourceTasksQuery
        {
            get
            {
                return global::LightSwitchApplication.ProjectTask.DetailsClass.GetQuery(this, global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ProjectResourceTasks);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ProjectTask,
                global::LightSwitchApplication.ProjectTask.DetailsClass,
                global::LightSwitchApplication.ProjectTask.DetailsClass.IImplementation,
                global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>.Entry
                __ProjectTaskEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProjectTask.DetailsClass.__ProjectTask_CreateNew,
                    global::LightSwitchApplication.ProjectTask.DetailsClass.__ProjectTask_Created,
                    global::LightSwitchApplication.ProjectTask.DetailsClass.__ProjectTask_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ProjectTask __ProjectTask_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ProjectTask> es)
            {
                return new global::LightSwitchApplication.ProjectTask(es);
            }
            private static void __ProjectTask_Created(global::LightSwitchApplication.ProjectTask e)
            {
                e.ProjectTask_Created();
            }
            private static bool __ProjectTask_AllowSaveWithErrors(global::LightSwitchApplication.ProjectTask e)
            {
                bool result = false;
                e.ProjectTask_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime> DueDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DueDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> Priority
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Priority) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal> PercentCompleted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.PercentCompleted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>> DateStarted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateStarted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>> DateCompleted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.DateCompleted) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project> Project
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask> ProjectResourceTasks
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ProjectResourceTasks) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new string Description { get; set; }
                new global::System.DateTime DueDate { get; set; }
                new string Priority { get; set; }
                new string Status { get; set; }
                new decimal PercentCompleted { get; set; }
                new global::System.Nullable<global::System.DateTime> DateStarted { get; set; }
                new global::System.Nullable<global::System.DateTime> DateCompleted { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Project { get; set; }
                new global::System.Collections.IEnumerable ProjectResourceTasks { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime>.Entry
                    DueDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime>.Entry(
                        "DueDate",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DueDate_OnValueChanged);
                private static void _DueDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._DueDate, sf);
                }
                private static bool _DueDate_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.DueDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _DueDate_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DueDate_Validate(r);
                }
                private static global::System.DateTime _DueDate_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.DueDate;
                }
                private static void _DueDate_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DueDate = global::LightSwitchApplication.ProjectTask.DetailsClass.TruncateDate(v);
                }
                private static void _DueDate_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.DueDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    Priority = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "Priority",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Priority_OnValueChanged);
                private static void _Priority_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Priority, sf);
                }
                private static bool _Priority_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Priority_IsReadOnly(ref result);
                    return result;
                }
                private static void _Priority_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Priority_Validate(r);
                }
                private static string _Priority_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Priority;
                }
                private static void _Priority_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Priority = v;
                }
                private static void _Priority_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Priority_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "Status",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Status_OnValueChanged);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static bool _Status_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Status_IsReadOnly(ref result);
                    return result;
                }
                private static void _Status_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static string _Status_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Status;
                }
                private static void _Status_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Status = v;
                }
                private static void _Status_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Status_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal>.Entry
                    PercentCompleted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal>.Entry(
                        "PercentCompleted",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._PercentCompleted_OnValueChanged);
                private static void _PercentCompleted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._PercentCompleted, sf);
                }
                private static bool _PercentCompleted_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.PercentCompleted_IsReadOnly(ref result);
                    return result;
                }
                private static void _PercentCompleted_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PercentCompleted_Validate(r);
                }
                private static decimal _PercentCompleted_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.PercentCompleted;
                }
                private static void _PercentCompleted_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.PercentCompleted = v;
                }
                private static void _PercentCompleted_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.PercentCompleted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateStarted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateStarted",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateStarted_OnValueChanged);
                private static void _DateStarted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._DateStarted, sf);
                }
                private static bool _DateStarted_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.DateStarted_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateStarted_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateStarted_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateStarted_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.DateStarted;
                }
                private static void _DateStarted_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateStarted = global::LightSwitchApplication.ProjectTask.DetailsClass.TruncateDate(v);
                }
                private static void _DateStarted_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.DateStarted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DateCompleted = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DateCompleted",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._DateCompleted_OnValueChanged);
                private static void _DateCompleted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._DateCompleted, sf);
                }
                private static bool _DateCompleted_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.DateCompleted_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateCompleted_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateCompleted_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DateCompleted_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.DateCompleted;
                }
                private static void _DateCompleted_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DateCompleted = global::LightSwitchApplication.ProjectTask.DetailsClass.TruncateDate(v);
                }
                private static void _DateCompleted_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.DateCompleted_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project>.Entry
                    Project = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project>.Entry(
                        "Project",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_ComputeIsReadOnly,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_Validate,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_GetCoreImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_GetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_SetImplementationValue,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_Refresh,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._Project_OnValueChanged);
                private static void _Project_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._Project, sf);
                }
                private static bool _Project_ComputeIsReadOnly(global::LightSwitchApplication.ProjectTask e)
                {
                    bool result = false;
                    e.Project_IsReadOnly(ref result);
                    return result;
                }
                private static void _Project_Validate(global::LightSwitchApplication.ProjectTask e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Project_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Project_GetCoreImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.Project;
                }
                private static global::LightSwitchApplication.Project _Project_GetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Project, global::LightSwitchApplication.Project.DetailsClass>(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project, ref d._Project);
                }
                private static void _Project_SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass d, global::LightSwitchApplication.Project v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project, ref d._Project, (i, ev) => i.Project = ev, v);
                }
                private static void _Project_Refresh(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.Project, ref d._Project);
                }
                private static void _Project_OnValueChanged(global::LightSwitchApplication.ProjectTask e)
                {
                    e.Project_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask>.Entry
                    ProjectResourceTasks = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask>.Entry(
                        "ProjectResourceTasks",
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ProjectResourceTasks_Stub,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ProjectResourceTasks_GetReferencedEntities,
                        global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties._ProjectResourceTasks_GetEntityCollection);
                private static void _ProjectResourceTasks_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectTask.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask>.Data> c, global::LightSwitchApplication.ProjectTask.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjectResourceTasks, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProjectResourceTask> _ProjectResourceTasks_GetReferencedEntities(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProjectResourceTask, global::LightSwitchApplication.ProjectResourceTask.DetailsClass>(global::LightSwitchApplication.ProjectTask.DetailsClass.PropertySetProperties.ProjectResourceTasks, ref d._ProjectResourceTasks);
                }
                private static global::System.Collections.IEnumerable _ProjectResourceTasks_GetEntityCollection(global::LightSwitchApplication.ProjectTask.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjectResourceTasks;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.DateTime>.Data _DueDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _Priority;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, decimal>.Data _PercentCompleted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateStarted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DateCompleted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.Project>.Data _Project;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ProjectTask, global::LightSwitchApplication.ProjectTask.DetailsClass, global::LightSwitchApplication.ProjectResourceTask>.Data _ProjectResourceTasks;
            
        }
    
        #endregion
    }
    
    #endregion
}
