//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Can Edit Client Contacts
        /// </summary>
        public const string CanEditClientContacts = "LightSwitchApplication:CanEditClientContacts";
        /// <summary>
        /// Can Edit Clients
        /// </summary>
        public const string CanEditClients = "LightSwitchApplication:CanEditClients";
        /// <summary>
        /// Can Edit Employees
        /// </summary>
        public const string CanEditEmployees = "LightSwitchApplication:CanEditEmployees";
        /// <summary>
        /// Can Edit Employees Skills
        /// </summary>
        public const string CanEditEmployeesSkills = "LightSwitchApplication:CanEditEmployeesSkills";
        /// <summary>
        /// Can Edit Project Resources
        /// </summary>
        public const string CanEditProjectResources = "LightSwitchApplication:CanEditProjectResources";
        /// <summary>
        /// Can Edit Project Resource Tasks
        /// </summary>
        public const string CanEditProjectResourceTasks = "LightSwitchApplication:CanEditProjectResourceTasks";
        /// <summary>
        /// Can Edit Project Risks
        /// </summary>
        public const string CanEditProjectRisks = "LightSwitchApplication:CanEditProjectRisks";
        /// <summary>
        /// Can Edit Projects
        /// </summary>
        public const string CanEditProjects = "LightSwitchApplication:CanEditProjects";
        /// <summary>
        /// Can Edit Project Tasks
        /// </summary>
        public const string CanEditProjectTasks = "LightSwitchApplication:CanEditProjectTasks";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
